apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw== 
  rmq-pass: Z3Vlc3Q=

# secrets are encoded in base64 in commandline and then coppied here
# All parameters, including secrets should be derived from the application.properties file
